TRANSLATIONS = {
    "ru": {
        "app_title": "Vexapay Disassembler",
        "open_file_btn": "Открыть файл...",
        "export_asm_btn": "Экспорт в .asm...",
        "settings_btn": "Настройки",
        "functions_tab": "Функции",
        "address_col": "Адрес",
        "name_col": "Имя",
        "rename_menu": "Переименовать",
        "blocks_tab": "Basic Blocks",
        "classes_tab": "Классы",
        "class_name_col": "Имя класса",
        "variables_tab": "Переменные",
        "type_col": "Тип",
        "strings_tab": "Строки",
        "section_col": "Секция",
        "string_col": "Строка",
        "settings_components_tab": "Компоненты",
        "toolbox_components_group": "Компоненты Toolbox",
        "signatures_tab": "Сигнатуры",
        "signatures_not_found": "Совпадений по сигнатурам не найдено",
        "hex_view_tab": "Hex-редактор",
        "value_col": "Значение",
        "info_tab": "Info",
        "imports_tab": "Imports",
        "exports_tab": "Exports",
        "addr_name_col": "Адрес и Имя",
        "explorer_tab": "Explorer",
        "extract_menu": "Извлечь...",
        "search_label": "Поиск:",
        "find_next_btn": "Далее",
        "find_prev_btn": "Назад",
        "search_title": "Поиск",
        "search_no_match": "Не найдено совпадений для '{query}'",
        "open_pe_file_title": "Выберите PE файл",
        "executable_files": "Executable files",
        "all_files": "All files",
        "error_title": "Ошибка",
        "invalid_pe_file": "Файл не является валидным PE файлом.\n{e}",
        "file_not_found": "Файл не найден по пути '{filepath}'",
        "unusual_entry_point_title": "Нестандартная точка входа",
        "unusual_entry_point_msg": "Точка входа (RVA: 0x{rva:x}) находится вне известных секций. Файл может быть упакован, поврежден или иметь необычную структуру.\n\nБудет предпринята попытка анализа первой исполняемой секции.",
        "critical_error_title": "Критическая ошибка",
        "no_executable_section": "Не удалось найти ни одной исполняемой секции в файле. Анализ невозможен.",
        "warning_title": "Предупреждение",
        "section_not_executable": "Секция '{name}', содержащая точку входа, не помечена как исполняемая. Анализ может быть некорректным.",
        "dotnet_analysis_header": "; --- Анализ сборки .NET: {filename} ---",
        "dotnet_analysis_body": (
            "; Это сборка .NET. Основной код представлен в виде Common Intermediate Language (CIL),\n"
            "; а не в виде нативного кода x86. Он компилируется в машинный код (JIT) во время выполнения.\n\n"
            "; Полноценное дизассемблирование CIL не поддерживается. Вместо этого, используйте вкладки:\n"
            ";  - 'Классы' для просмотра управляемых классов и методов.\n"
            ";  - 'Info' для общей информации о сборке.\n"
            ";  - 'Explorer' для просмотра структуры файла.\n"
        ),
        "functions_not_found": "Функции не найдены",
        "blocks_analysis_disabled": "Анализ блоков отключен",
        "block_prefix": "Блок",
        "classes_not_found": "Классы не найдены",
        "base_classes_node": "[Base Classes]",
        "methods_node": "[Methods]",
        "virtual_methods_node": "[Virtual Methods]",
        "variables_not_found": "Переменные не найдены",
        "info_not_available": "Информация не доступна.",
        "info_hashes": "Hashes",
        "info_general": "General",
        "info_analysis": "Analysis",
        "info_compiler": "Compiler",
        "info_language": "Language",
        "info_packer": "Packer",
        "info_security": "Security Features",
        "sec_aslr": "ASLR (Dynamic Base)",
        "sec_dep": "DEP (NX Compat)",
        "sec_safeseh": "SafeSEH",
        "sec_cfg": "Control Flow Guard (CFG)",
        "sec_auth": "Authenticode Signature",
        "sec_tls": "TLS Callbacks",
        "sec_entropy": "High Entropy Sections",
        "present": "Present",
        "absent": "Absent",
        "info_sections": "Sections",
        "col_name": "Name",
        "col_address": "Address",
        "col_size": "Size",
        "col_entropy": "Entropy",
        "col_flags": "Flags",
        "info_anti_analysis": "Anti-Analysis",
        "imports_not_found": "Импорты не найдены",
        "exports_not_found": "Экспорты не найдены",
        "structure_not_found": "Структура не найдена",
        "entropy_suffix": " (Энтропия: {entropy:.2f})",
        "size_kb": " ({size} KB)",
        "size_b": " ({size} B)",
        "xrefs_title": "Перекрестные ссылки",
        "xrefs_not_found_var": "Не найдено ссылок на переменную по адресу 0x{address:x}",
        "xrefs_not_found_imp": "Не найдено ссылок на импорт (адрес IAT: 0x{address:x})",
        "save_file_title": "Сохранить файл '{name}'",
        "done_title": "Готово",
        "file_extracted_success": "Файл '{name}' успешно извлечен.",
        "extract_error_title": "Ошибка извлечения",
        "file_extract_error": "Не удалось извлечь файл.\n{e}",
        "select_folder_title": "Выберите папку для извлечения '{name}'",
        "folder_extracted_success": "Папка '{name}' успешно извлечена в:\n{path}",
        "folder_extract_error": "Не удалось извлечь папку.\n{e}",
        "disasm_header": "; --- Дизассемблирование секции {section} из '{filename}' ---",
        "base_addr_header": "; --- Базовый адрес: 0x{address:x} ---",
        "save_as_title": "Сохранить как...",
        "asm_files": "Assembly files",
        "txt_files": "Text files",
        "all_files_filter": "All files",
        "save_success": "Результат сохранен в файл:\n{filepath}",
        "save_error_title": "Ошибка сохранения",
        "save_error_msg": "Не удалось сохранить файл.\n{e}",
        "rename_func_prompt": "Введите новое имя для 0x{address:x}:",
        "rename_func_error": "Не удалось переименовать функцию.",
        "show_xrefs_menu": "Показать перекрестные ссылки",
        "copy_line_menu": "Копировать строку",
        "xrefs_not_found": "Не найдено ссылок на 0x{address:x}",
        "select_section_title": "Выберите секцию для анализа",
        "col_va": "Адрес (VA)",
        "col_vsize": "Вирт. размер",
        "col_rsize": "RAW размер",
        "analyze_btn": "Анализировать",
        "cancel_btn": "Отмена",
        "xrefs_for_addr_title": "Ссылки на 0x{address:x}",
        "col_function": "Функция",
        "col_instruction": "Инструкция",
        "no_data": "(нет данных)",
        "settings_title": "Настройки",
        "appearance_tab": "Вид",
        "dark_theme_checkbox": "Темная тема",
        "listing_tab": "Листинг",
        "display_group": "Отображение",
        "show_padding_checkbox": "Показывать байты-заполнители (int3, nop)",
        "show_bytes_checkbox": "Показывать байты инструкции",
        "uppercase_mnemonics_checkbox": "Отображать мнемоники в верхнем регистре",
        "show_errors_checkbox": "Подсвечивать ошибки анализа красным",
        "analysis_tab": "Анализ",
        "file_loading_group": "Загрузка файла",
        "auto_section_checkbox": "Автоматический поиск секции для анализа",
        "func_analysis_group": "Анализ функций",
        "prologue_heuristic_checkbox": "Искать стандартные прологи",
        "separator_heuristic_checkbox": "Искать код после ret/jmp",
        "padding_heuristic_checkbox": "Искать код после блоков-заполнителей",
        "analyze_blocks_checkbox": "Анализировать базовые блоки",
        "other_analyzers_group": "Прочие анализаторы",
        "analyze_xrefs_checkbox": "Анализировать перекрестные ссылки (xrefs)",
        "analyze_classes_checkbox": "Анализировать классы C++",
        "analyze_vars_checkbox": "Анализировать переменные в секциях данных",
        "analyze_all_sections_checkbox": "Искать сигнатуры по всему файлу (рекомендуется)",
        "analyze_signatures_checkbox": "Искать по сигнатурам (Beta)",
        "enable_functions_tab": "Вкладка 'Функции'",
        "enable_blocks_tab": "Вкладка 'Basic Blocks'",
        "enable_classes_tab": "Вкладка 'Классы'",
        "enable_variables_tab": "Вкладка 'Переменные'",
        "enable_signatures_tab": "Вкладка 'Сигнатуры'",
        "enable_strings_tab": "Вкладка 'Строки'",
        "enable_info_tab": "Вкладка 'Info'",
        "enable_imports_tab": "Вкладка 'Imports/Exports'",
        "enable_explorer_tab": "Вкладка 'Explorer'",
        "analyze_antidebug_checkbox": "Анализировать Anti-Debug/VM техники",
        "beta_warning": "(Beta, возможны ложные срабатывания)",
        "reset_btn": "Сбросить",
        "ok_btn": "OK",
        "pefile_not_found_title": "Критическая ошибка",
        "pefile_not_found_msg": "Библиотека 'pefile' не найдена.\n\nПожалуйста, установите ее командой:\npip install pefile",
        "save_settings_error_title": "Ошибка сохранения настроек",
        "save_settings_error_msg": "Не удалось сохранить настройки.\n{e}",
        "critical_startup_error_title": "Критическая ошибка при запуске",
        "unexpected_startup_error_msg": "Произошла непредвиденная ошибка:\n\n{e}\n\nПриложение будет закрыто.",
        "language_label": "Язык интерфейса:",
        "restart_required_title": "Требуется перезапуск",
        "restart_required_message": "Изменения языка или компонентов интерфейса вступят в силу после перезапуска приложения.",
    },
    "en": {
        "app_title": "Vexapay Disassembler",
        "open_file_btn": "Open File...",
        "export_asm_btn": "Export to .asm...",
        "settings_btn": "Settings",
        "functions_tab": "Functions",
        "address_col": "Address",
        "name_col": "Name",
        "rename_menu": "Rename",
        "blocks_tab": "Basic Blocks",
        "classes_tab": "Classes",
        "class_name_col": "Class Name",
        "variables_tab": "Variables",
        "type_col": "Type",
        "strings_tab": "Strings",
        "section_col": "Section",
        "string_col": "String",
        "settings_components_tab": "Components",
        "toolbox_components_group": "Toolbox Components",
        "signatures_tab": "Signatures",
        "signatures_not_found": "No signature matches found",
        "hex_view_tab": "Hex View",
        "value_col": "Value",
        "info_tab": "Info",
        "imports_tab": "Imports",
        "exports_tab": "Exports",
        "addr_name_col": "Address & Name",
        "explorer_tab": "Explorer",
        "extract_menu": "Extract...",
        "search_label": "Search:",
        "find_next_btn": "Next",
        "find_prev_btn": "Previous",
        "search_title": "Search",
        "search_no_match": "No matches found for '{query}'",
        "open_pe_file_title": "Select a PE file",
        "executable_files": "Executable files",
        "all_files": "All files",
        "error_title": "Error",
        "invalid_pe_file": "The file is not a valid PE file.\n{e}",
        "file_not_found": "File not found at path '{filepath}'",
        "unusual_entry_point_title": "Unusual Entry Point",
        "unusual_entry_point_msg": "The entry point (RVA: 0x{rva:x}) is outside known sections. The file might be packed, corrupted, or have an unusual structure.\n\nAttempting to analyze the first executable section.",
        "critical_error_title": "Critical Error",
        "no_executable_section": "Could not find any executable section in the file. Analysis is not possible.",
        "warning_title": "Warning",
        "section_not_executable": "The section '{name}' containing the entry point is not marked as executable. Analysis may be incorrect.",
        "dotnet_analysis_header": "; --- Analyzing .NET Assembly: {filename} ---",
        "dotnet_analysis_body": (
            "; This is a .NET assembly. The main code is in Common Intermediate Language (CIL),\n"
            "; not native x86 code. It is Just-In-Time (JIT) compiled at runtime.\n\n"
            "; Full CIL disassembly is not supported. Instead, use the tabs:\n"
            ";  - 'Classes' to view managed classes and methods.\n"
            ";  - 'Info' for general assembly information.\n"
            ";  - 'Explorer' to view the file structure.\n"
        ),
        "functions_not_found": "Functions not found",
        "blocks_analysis_disabled": "Block analysis is disabled",
        "block_prefix": "Block",
        "classes_not_found": "Classes not found",
        "base_classes_node": "[Base Classes]",
        "methods_node": "[Methods]",
        "virtual_methods_node": "[Virtual Methods]",
        "variables_not_found": "Variables not found",
        "info_not_available": "Information not available.",
        "info_hashes": "Hashes",
        "info_general": "General",
        "info_analysis": "Analysis",
        "info_compiler": "Compiler",
        "info_language": "Language",
        "info_packer": "Packer",
        "info_security": "Security Features",
        "sec_aslr": "ASLR (Dynamic Base)",
        "sec_dep": "DEP (NX Compat)",
        "sec_safeseh": "SafeSEH",
        "sec_cfg": "Control Flow Guard (CFG)",
        "sec_auth": "Authenticode Signature",
        "sec_tls": "TLS Callbacks",
        "sec_entropy": "High Entropy Sections",
        "present": "Present",
        "absent": "Absent",
        "info_sections": "Sections",
        "col_name": "Name",
        "col_address": "Address",
        "col_size": "Size",
        "col_entropy": "Entropy",
        "col_flags": "Flags",
        "info_anti_analysis": "Anti-Analysis",
        "imports_not_found": "Imports not found",
        "exports_not_found": "Exports not found",
        "structure_not_found": "Structure not found",
        "entropy_suffix": " (Entropy: {entropy:.2f})",
        "size_kb": " ({size} KB)",
        "size_b": " ({size} B)",
        "xrefs_title": "Cross-References",
        "xrefs_not_found_var": "No references found to variable at address 0x{address:x}",
        "xrefs_not_found_imp": "No references found to import (IAT address: 0x{address:x})",
        "save_file_title": "Save file '{name}'",
        "done_title": "Done",
        "file_extracted_success": "File '{name}' was successfully extracted.",
        "extract_error_title": "Extraction Error",
        "file_extract_error": "Could not extract the file.\n{e}",
        "select_folder_title": "Select a folder to extract '{name}'",
        "folder_extracted_success": "Folder '{name}' was successfully extracted to:\n{path}",
        "folder_extract_error": "Could not extract the folder.\n{e}",
        "disasm_header": "; --- Disassembling section {section} from '{filename}' ---",
        "base_addr_header": "; --- Base Address: 0x{address:x} ---",
        "save_as_title": "Save As...",
        "asm_files": "Assembly files",
        "txt_files": "Text files",
        "all_files_filter": "All files",
        "save_success": "Result saved to file:\n{filepath}",
        "save_error_title": "Save Error",
        "save_error_msg": "Could not save the file.\n{e}",
        "rename_func_prompt": "Enter new name for 0x{address:x}:",
        "rename_func_error": "Could not rename the function.",
        "show_xrefs_menu": "Show Cross-References",
        "copy_line_menu": "Copy Line",
        "xrefs_not_found": "No references found to 0x{address:x}",
        "select_section_title": "Select Section for Analysis",
        "col_va": "Address (VA)",
        "col_vsize": "Virtual Size",
        "col_rsize": "RAW Size",
        "analyze_btn": "Analyze",
        "cancel_btn": "Cancel",
        "xrefs_for_addr_title": "References to 0x{address:x}",
        "col_function": "Function",
        "col_instruction": "Instruction",
        "no_data": "(no data)",
        "settings_title": "Settings",
        "appearance_tab": "Appearance",
        "dark_theme_checkbox": "Dark theme",
        "listing_tab": "Listing",
        "display_group": "Display",
        "show_padding_checkbox": "Show padding bytes (int3, nop)",
        "show_bytes_checkbox": "Show instruction bytes",
        "uppercase_mnemonics_checkbox": "Display mnemonics in uppercase",
        "show_errors_checkbox": "Highlight analysis errors in red",
        "analysis_tab": "Analysis",
        "file_loading_group": "File Loading",
        "auto_section_checkbox": "Automatically find section to analyze",
        "func_analysis_group": "Function Analysis",
        "prologue_heuristic_checkbox": "Search for standard prologues",
        "separator_heuristic_checkbox": "Search for code after ret/jmp",
        "padding_heuristic_checkbox": "Search for code after padding blocks",
        "analyze_blocks_checkbox": "Analyze basic blocks",
        "other_analyzers_group": "Other Analyzers",
        "analyze_xrefs_checkbox": "Analyze cross-references (xrefs)",
        "analyze_classes_checkbox": "Analyze C++ classes",
        "analyze_vars_checkbox": "Analyze variables in data sections",
        "analyze_all_sections_checkbox": "Scan entire file for signatures (recommended)",
        "analyze_signatures_checkbox": "Scan for signatures (Beta)",
        "enable_functions_tab": "Enable 'Functions' Tab",
        "enable_blocks_tab": "Enable 'Basic Blocks' Tab",
        "enable_classes_tab": "Enable 'Classes' Tab",
        "enable_variables_tab": "Enable 'Variables' Tab",
        "enable_signatures_tab": "Enable 'Signatures' Tab",
        "enable_strings_tab": "Enable 'Strings' Tab",
        "enable_info_tab": "Enable 'Info' Tab",
        "enable_imports_tab": "Enable 'Imports/Exports' Tab",
        "enable_explorer_tab": "Enable 'Explorer' Tab",
        "analyze_antidebug_checkbox": "Analyze Anti-Debug/VM techniques",
        "beta_warning": "(Beta, may have false positives)",
        "reset_btn": "Reset",
        "ok_btn": "OK",
        "pefile_not_found_title": "Critical Error",
        "pefile_not_found_msg": "The 'pefile' library was not found.\n\nPlease install it using the command:\npip install pefile",
        "save_settings_error_title": "Error Saving Settings",
        "save_settings_error_msg": "Could not save settings.\n{e}",
        "critical_startup_error_title": "Critical Startup Error",
        "unexpected_startup_error_msg": "An unexpected error occurred:\n\n{e}\n\nThe application will now close.",
        "language_label": "Interface Language:",
        "restart_required_title": "Restart Required",
        "restart_required_message": "Language or UI component changes will take effect after restarting the application.",
    }
}

class Translator:
    def __init__(self, lang="ru"):
        self.lang = lang
        if lang not in TRANSLATIONS:
            self.lang = "ru"
        self.translations = TRANSLATIONS[self.lang]

    def get(self, key):
        return self.translations.get(key, key)

translator = None

def init_translator(lang="ru"):
    global translator
    translator = Translator(lang)

def _(key):
    if translator is None:
        init_translator()
    return translator.get(key)